import { Step } from 'react-joyride';

export interface RouteStep extends Step {
  route?: string;
  skipNextOnNext?: boolean;
  hideNextButton?: boolean;
  clickOnNext?: boolean;
}

export const qaWorkflowSteps: RouteStep[] = [
  {
    target: 'body',
    route: '/qa-workspace/test-scope',
    title: 'Welcome to QA guide',
    content: 'This tour will walk you through the complete Quality Assurance lifecycle. You will learn how to define settings, write cases, execute runs, track bugs, and submit for final approval.',
    placement: 'center',
  },
  {
    target: '[data-tour="settings-scope-type"]',
    route: '/qa-workspace/settings',
    title: 'Scope Type',
    content: 'Click "Scope Type" in the sidebar to view the scope configurations.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-scope-type-btn"]', // The "+ New Scope Type" button
    route: '/qa-workspace/settings',
    title: 'Create Scope Type',
    content: 'Use this button to define a new Scope Type to categorize your Test Scopes.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-scope-priority-status"]',
    route: '/qa-workspace/settings',
    title: 'Priority & Status',
    content: 'You can also customize the Priorities and Statuses for your Test Scopes here.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-scope-priority-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Priority/Status',
    content: 'Use this button to add a new Priority or Status to your Test Scopes.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-cases"]',
    route: '/qa-workspace/settings',
    title: 'Modules',
    content: 'Manage the Modules used to organize your Test Cases here.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-module-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Module',
    content: 'Use this button to add a new Module to your project.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-bugs"]',
    route: '/qa-workspace/settings',
    title: 'Bug Definitions',
    content: 'Define the default Bug properties (Severity, Type, Priority). Default templates are already created for you!',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-bug-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Bug Definition',
    content: 'Use this button to define a new Severity, Type, or Priority for your Bugs.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="test-scope"]',
    route: '/qa-workspace/test-scope',
    title: 'Create Scope',
    content: 'Define what needs to be tested based on the configurations you just reviewed. Test Scope establishes the requirements and areas that need QA validation.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="test-cases"]',
    route: '/qa-workspace/test-cases',
    title: 'Test Cases & Module Cases',
    content: 'Create the parent test scenarios. Once you create a case, you can add detailed Module Test Cases inside it to define specific step-by-step instructions.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="test-suites"]',
    route: '/qa-workspace/test-suites',
    title: 'Test Suites',
    content: 'Organize your related Test Cases into reusable suites for structured test execution.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="test-runs"]',
    route: '/qa-workspace/test-runs',
    title: 'Test Runs',
    content: 'Execute your suites and record outcomes. If a run fails, the failed case is automatically logged as a bug in the Bug List.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="new-bug-btn"]',
    route: '/qa-workspace/bug-list',
    title: 'Bug Tracking & Tickets',
    content: 'Review bugs generated from failed runs. You can easily turn these bugs into engineering tickets using Manual entry, AI generation, or Mapping to existing tickets.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-submission"]',
    route: '/qa-workspace/qa-submissions',
    title: 'QA Submission',
    content: 'Submit the completed QA cycle for review once testing and bug resolution are complete.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-signoff"]',
    route: '/qa-workspace/approvals',
    title: 'QA Sign-off',
    content: 'Complete the QA lifecycle with a formal sign-off once the required validation is complete.',
    placement: 'bottom',
  },
  {
    target: 'body',
    title: 'You are all set!',
    content: 'You are now ready to manage your entire QA lifecycle. Use these tools to ensure top-notch quality for your products.',
    placement: 'center',
  }
];

export const ticketsTourSteps: RouteStep[] = [
  {
    target: 'body',
    route: '/dashboard',
    title: 'Welcome to Tickets & Sprints',
    content: 'This tour will guide you step by step through projects, ticket configurations, sprint planning & activation, and the complete ticket lifecycle.',
    placement: 'center',
  },
  {
    target: '[data-tour="tickets-project-setup"]',
    route: '/projects/manage',
    title: 'Project Foundation',
    content: 'Tickets and Sprints work based on Projects. Make sure you have created your Project first before planning sprints and tickets.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-platform"]',
    route: '/tickets/settings',
    title: 'Platforms Configuration',
    content: 'Configure core team platforms and delivery departments for your organization.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-create-platform-btn"]',
    route: '/tickets/settings',
    title: 'Add Platform',
    content: 'Use this button to add a new Platform option to your workspace.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-stack"]',
    route: '/tickets/settings',
    title: 'Technology Stacks',
    content: 'Manage available technology stacks used for project tagging and ticket filtering.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-create-stack-btn"]',
    route: '/tickets/settings',
    title: 'Add Technology Stack',
    content: 'Use this button to add a new Tech Stack classification.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-priority"]',
    route: '/tickets/settings',
    title: 'Priorities & Urgency',
    content: 'Define priority levels and visual indicators for your tickets.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-create-priority-btn"]',
    route: '/tickets/settings',
    title: 'Add Priority',
    content: 'Use this button to define a new Priority level for tickets.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-taskLevel"]',
    route: '/tickets/settings',
    title: 'Complexity & Story Points',
    content: 'Configure task difficulty levels and story point weighting for estimation.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-create-taskLevel-btn"]',
    route: '/tickets/settings',
    title: 'Add Complexity Level',
    content: 'Use this button to define a new task complexity rating.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-taskType"]',
    route: '/tickets/settings',
    title: 'Work Types',
    content: 'Define classifications for your tasks (e.g. Feature, Bug, Maintenance, Refactor).',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-create-taskType-btn"]',
    route: '/tickets/settings',
    title: 'Add Work Type',
    content: 'Use this button to add a new Work Type categorization.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-status"]',
    route: '/tickets/settings',
    title: 'Lifecycle Statuses',
    content: 'Set up your workflow lifecycle stages (To Do, In Progress, Code Review, Completed).',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-create-status-btn"]',
    route: '/tickets/settings',
    title: 'Add Lifecycle Status',
    content: 'Use this button to define a new lifecycle status for your workflow.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-create-sprint"]',
    route: '/tickets/plans',
    title: 'Plan New Sprint',
    content: 'Click "Plan New Sprint" to start a new sprint cycle for your project with defined timelines and objectives.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-activate-sprint"]',
    route: '/tickets/plans',
    title: 'Activate Sprint',
    content: 'Click "Start Sprint" to activate your planned sprint. Note: Only one sprint can be active per project at any time. Complete your active sprint before activating another.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-project-view"]',
    route: '/tickets/select',
    title: 'Select Project & Sprint Board',
    content: 'Switch projects and access your active sprint board or backlog view.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-create"]',
    route: '/tickets/select',
    title: 'Create Tickets',
    content: 'Create tickets using Instant Creation for fast typing, Manual Creation for full details, or AI generation with Zai. Note: New tickets start in the Backlog by default.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-recent-created-btn"]',
    route: '/tickets/select',
    title: 'Created Ticket Overview',
    content: 'Click this created ticket button to immediately open its details drawer.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-drawer-add-sprint"]',
    route: '/tickets/select',
    title: 'Add to Sprint',
    content: 'Click "Add to Sprint" to immediately move this ticket from the backlog into your active sprint.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-drawer-create-doc"]',
    route: '/tickets/select',
    title: 'Create & Link Docs',
    content: 'Click "Create Doc" to link or generate a new Document Hub wiki, runbook, or technical spec for this ticket.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-drawer-share"]',
    route: '/tickets/select',
    title: 'Share Ticket',
    content: 'Copy and share the ticket link with teammates or external collaborators.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-trash-archive"]',
    route: '/tickets/select',
    title: 'Trash & Archive',
    content: 'Move completed or unwanted tickets to the Archive or Trash to maintain a clean board.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-buckets-create"]',
    route: '/tickets/buckets',
    title: 'Buckets',
    content: 'Buckets allow you to organize tasks outside of sprints. You can create them from the Buckets page or during sprint completion.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-complete-sprint"]',
    route: '/tickets/select',
    title: 'Complete Sprint',
    content: 'When your sprint finishes, click "Complete Sprint" directly from the active sprint header to resolve remaining tasks and complete the sprint.',
    placement: 'bottom',
  },
  {
    target: 'body',
    title: 'You are all set!',
    content: 'You are now ready to manage your entire Project & Ticket lifecycle. Plan sprints, track progress, and ship with confidence!',
    placement: 'center',
  }
];

export const documentHubTourSteps: RouteStep[] = [
  {
    target: 'body',
    route: '/documenthub',
    title: 'Welcome to Document Hub',
    content: 'Document Hub is your central knowledge base for engineering specs, architecture wikis, runbooks, and project documentation.',
    placement: 'center',
  },
  {
    target: '[data-tour="dochub-create-hub-btn"]',
    route: '/documenthub',
    title: 'Create Document Hub',
    content: 'Click here to create a new Document Hub. Start from scratch with a blank hub or generate a structured template with Zai AI.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-workspace-new-btn"]',
    route: '/documenthub',
    title: 'Create Folders & Documents',
    content: 'Inside any hub, use "+ New" to organize content into nested folders and rich BlockNote documents with embeds, callouts, and diagrams.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-preview-btn"]',
    route: '/documenthub',
    title: 'Preview & Split View',
    content: 'Easily switch between Edit, Preview, and Split views to review how your formatted markdown, media embeds, and tables look in real time.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-history-btn"]',
    route: '/documenthub',
    title: 'Version History',
    content: 'Access complete document revision history. Inspect previous versions, compare changes, and restore any earlier snapshot with 1 click.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-link-project-ticket"]',
    route: '/documenthub',
    title: 'Link Projects & Tickets',
    content: 'Attach your Document Hub directly to specific Projects and Tickets so developers have immediate context right where they work.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-visibility-btn"]',
    route: '/documenthub',
    title: 'Manage Visibility',
    content: 'Set visibility levels to Public (accessible by everyone in the workspace) or Private (restricted to invited team members).',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-share-btn"]',
    route: '/documenthub',
    title: 'Share & Collaborate',
    content: 'Share documentation with teammates, manage view or edit permissions, and generate shareable links for reviews.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-star-btn"]',
    route: '/documenthub',
    title: 'Star & Unstar Hubs',
    content: 'Star your most important or frequently visited document hubs to pin them to your favorites for instant 1-click access.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-upload-import"]',
    route: '/documenthub',
    title: 'Cloud Import & Upload',
    content: 'Easily upload files from My Computer or import existing docs directly from Google Drive, Notion, Zoho WorkDrive, and Microsoft OneDrive.',
    placement: 'bottom',
  },
  {
    target: 'body',
    title: 'You are all set with Document Hub!',
    content: 'You are ready to create, organize, and collaborate on documentation with your team!',
    placement: 'center',
  }
];
