import { Step } from 'react-joyride';

export interface RouteStep extends Step {
  route?: string;
  skipNextOnNext?: boolean;
  hideNextButton?: boolean;
  clickOnNext?: boolean;
  disableActive?: boolean;
  showProjectTourBtn?: boolean;
  showRoleTourBtn?: boolean;
  showOrgTourBtn?: boolean;
  spotlightClicks?: boolean;
  skipIfNotFound?: boolean;
}

export const qaWorkflowSteps: RouteStep[] = [
  {
    target: 'body',
    route: '/qa-workspace/test-scope',
    title: 'Welcome to QA guide',
    content: 'This tour will walk you through the complete Quality Assurance lifecycle. You will learn how to define settings, write cases, execute runs, track bugs, and submit for final approval.\n\nBefore moving forward, make sure you have created your Project first; otherwise, you can view the Project Tour.',
    placement: 'center',
    showProjectTourBtn: true,
  },
  {
    target: '[data-tour="settings-scope-scope_type"], [data-tour="settings-scope-type"]',
    route: '/qa-workspace/settings',
    title: 'Scope Type',
    content: 'Configure different types of scopes (e.g. Web, Mobile, API, Security) to categorize your testing domains.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-scope-type-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Scope Type',
    content: 'Use this button to define a new Scope Type to categorize your Test Scopes.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-scope-priority"]',
    route: '/qa-workspace/settings',
    title: 'Scope Priority',
    content: 'Customize priority levels (e.g. High, Medium, Low, Critical) for your Test Scopes to guide team focus.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-scope-priority-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Scope Priority',
    content: 'Use this button to add custom Priority designations for your Test Scopes.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-scope-status"]',
    route: '/qa-workspace/settings',
    title: 'Scope Status',
    content: 'Define lifecycle status workflows for Test Scopes (e.g. Draft, In Progress, In Review, Ready).',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-scope-status-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Scope Status',
    content: 'Use this button to configure new custom status stages for your Test Scopes.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-cases-modules"], [data-tour="settings-cases"]',
    route: '/qa-workspace/settings',
    title: 'Test Case Modules',
    content: 'Manage the functional modules and components used to organize Test Cases into logical groups.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-module-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Module',
    content: 'Use this button to create and register a new functional module for your project.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-cases-type"]',
    route: '/qa-workspace/settings',
    title: 'Testing Types',
    content: 'Categorize test cases by testing area or methodology (e.g., UI, Functional, API, Security).',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-type-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Testing Type',
    content: 'Use this button to add a new custom testing type taxonomy for your test cases.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-bug-severity"]',
    route: '/qa-workspace/settings',
    title: 'Bug Severity',
    content: 'Set up tenant-scoped bug severity options (e.g. Blocker, Critical, Major, Minor, Trivial) to evaluate defect impact.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-bug-severity-btn"], [data-tour="settings-create-bug-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Severity',
    content: 'Use this button to define a new Severity level for triage in the bug tracker.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-bug-type"]',
    route: '/qa-workspace/settings',
    title: 'Bug Type',
    content: 'Organize defect taxonomy across UI, Functional, Performance, Security, and API types.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-bug-type-btn"], [data-tour="settings-create-bug-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Bug Type',
    content: 'Use this button to add a new bug classification category tailored to your applications.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-bug-priority"]',
    route: '/qa-workspace/settings',
    title: 'Bug Priority',
    content: 'Define bug resolution priorities to communicate fix urgency across engineering teams.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="settings-create-bug-priority-btn"], [data-tour="settings-create-bug-btn"]',
    route: '/qa-workspace/settings',
    title: 'Create Bug Priority',
    content: 'Use this button to define customized bug resolution priority options.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-project-select"]',
    route: '/qa-workspace/test-scope',
    title: 'Project Switch',
    content: 'Use this dropdown to switch your active project context. Test scopes and configurations apply to your selected project.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="test-scope"]',
    route: '/qa-workspace/test-scope',
    title: 'Create Scope',
    content: 'Define what needs to be tested based on the configurations you just reviewed. Test Scope establishes the requirements and areas that need QA validation.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="approvals-tab-scopes"]',
    route: '/qa-workspace/approvals',
    title: 'Scope Approval',
    content: 'Once a Test Scope is created, submit it for Manager review. Click here to open the Scope Approvals queue where managers can evaluate, approve, or request revisions.',
    placement: 'right',
    spotlightClicks: true,
    clickOnNext: true,
  },
  {
    target: '[data-tour="scope-approvals-row"]',
    route: '/qa-workspace/approvals',
    title: 'Scope Approvals Queue',
    content: 'Here you can review the details of submitted test scopes and officially approve or send them back for revisions.',
    placement: 'bottom',
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="qa-project-select"]',
    route: '/qa-workspace/test-cases',
    title: 'Project Switch',
    content: 'Use this dropdown to switch your active project context. Test cases, suites, and runs are scoped to your selected project.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="test-cases"]',
    route: '/qa-workspace/test-cases',
    title: 'Create Test Case',
    content: 'Create high-level parent Test Cases to organize testing for specific features or functional domains.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="create-module-case-btn"]',
    route: '/qa-workspace/test-cases',
    title: 'Module Test Cases',
    content: 'Inside each parent Test Case, create granular Module Test Cases with detailed preconditions, execution steps, and expected outcomes before assembling Test Suites.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-project-select"]',
    route: '/qa-workspace/test-suites',
    title: 'Project Switch',
    content: 'Use this dropdown to switch your active project context. Test suites are built and managed within your selected project.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="test-suites"]',
    route: '/qa-workspace/test-suites',
    title: 'Test Suites',
    content: 'Organize your related Test Cases into reusable suites for structured test execution.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-project-select"]',
    route: '/qa-workspace/test-runs',
    title: 'Project Switch',
    content: 'Use this dropdown to switch your active project context. You can only execute test runs for your currently active project.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="test-runs"]',
    route: '/qa-workspace/test-runs',
    title: 'Create Test Run',
    content: 'Execute your test suites and track live testing outcomes. Click here to initialize a new test execution run.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-run-details-btn"]',
    route: '/qa-workspace/test-runs',
    title: 'Execution & Case Details',
    content: 'Open the test run to inspect execution cases. Click "Details" to review preconditions, reproduction steps, and expected outcomes.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-run-pass-btn"]',
    route: '/qa-workspace/test-runs',
    title: 'Mark as Passed',
    content: 'Click "Pass" when the observed application behavior successfully satisfies all test criteria and expected results.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-run-fail-btn"]',
    route: '/qa-workspace/test-runs',
    title: 'Mark as Failed',
    content: 'Click "Fail" if an error, broken flow, or deviation from expected behavior is observed during testing.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-run-blocked-btn"]',
    route: '/qa-workspace/test-runs',
    title: 'Mark as Blocked',
    content: 'Click "Blocked" when third-party downtime, missing permissions, or upstream dependencies prevent executing this test case.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-run-fail-buglist"]',
    route: '/qa-workspace/test-runs',
    title: 'Add to Buglist',
    content: 'If any test case fails during execution, click "Add to Buglist" to immediately convert the failed test into a bug in your bug tracker.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="qa-project-select"]',
    route: '/qa-workspace/bug-list',
    title: 'Choose Project',
    content: 'Select your active Project to view its associated bug collections, folders, sheets, and defect metrics.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="bug-create-folder-btn"]',
    route: '/qa-workspace/bug-list',
    title: 'Create Folder',
    content: 'Create organized folders and collections to group your bug sheets by release, sprint, or component.',
    placement: 'right',
  },
  {
    target: '[data-tour="bug-create-sheet-btn"]',
    route: '/qa-workspace/bug-list',
    title: 'Create Sheet',
    content: 'Add dedicated bug sheets inside folders to capture and triage defects for specific testing cycles.',
    placement: 'right',
  },
  {
    target: '[data-tour="bug-sheet-node"]',
    route: '/qa-workspace/bug-list',
    title: 'Select Sheet',
    content: 'Click on the sheet to open it. Selecting an active sheet displays its defect table and enables bug creation.',
    placement: 'right',
    spotlightClicks: true,
    clickOnNext: true,
  },
  {
    target: '[data-tour="bug-quick-add"]',
    route: '/qa-workspace/bug-list',
    title: 'Quick Add Bug',
    content: 'Type a bug title directly into this field and press Enter to instantly log a defect without opening a drawer.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="new-bug-btn"]',
    route: '/qa-workspace/bug-list',
    title: 'Full Bug Creation',
    content: 'Click "+ New Bug" to capture detailed defect reports including severity, reproduction steps, screenshots, logs, and module tagging.',
    placement: 'right',
  },
  {
    target: '[data-tour="bug-row-actions"]',
    route: '/qa-workspace/bug-list',
    title: 'Edit, Archive & Recurring',
    content: 'Manage the full bug lifecycle: edit details, mark defects as Recurring to preserve issue history across runs, or archive resolved bugs.',
    placement: 'left',
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="bug-list-ticket"]',
    route: '/qa-workspace/bug-list',
    title: 'Convert to Tickets',
    content: 'Convert bugs into actionable developer tickets using Manual entry, AI generation, or mapping to existing tasks.',
    placement: 'bottom',
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="qa-project-select"]',
    route: '/qa-workspace/coverage-map',
    title: 'Project Switch',
    content: 'Select your project to view its specific coverage map.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="coverage-health-bands"]',
    route: '/qa-workspace/coverage-map',
    title: 'Health Bands',
    content: 'Monitor the health of your modules. These bands show pass rates based on the latest runs for each module.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="coverage-gaps-filter"]',
    route: '/qa-workspace/coverage-map',
    title: 'Identify Coverage Gaps',
    content: 'Use the "Gaps only" filter to quickly spot modules that are missing test cases or haven\'t been executed yet.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="coverage-module-tree"]',
    route: '/qa-workspace/coverage-map',
    title: 'Module Details',
    content: 'Click on any module to drill down into its specific scopes, cases, suites, and runs to see exactly what was tested.',
    placement: 'right',
  },
  {
    target: '[data-tour="qa-submission"]',
    route: '/qa-workspace/qa-submissions',
    title: 'QA Submission',
    content: 'Submit the completed QA cycle for review once testing and bug resolution are complete.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="approvals-queue"]',
    route: '/qa-workspace/approvals',
    title: 'Approval Queue',
    content: 'Navigate through different stages of the approval lifecycle: Awaiting Decision, Re-testing, Approved, and QA Signed-off.',
    placement: 'right',
  },
  {
    target: '[data-tour="qa-signoff"]',
    route: '/qa-workspace/approvals',
    title: 'QA Sign-off',
    content: 'Complete the QA lifecycle with a formal sign-off once the required validation is complete.',
    placement: 'bottom',
    skipIfNotFound: true,
  },
  {
    target: 'body',
    title: 'You are all set!',
    content: 'You are now ready to manage your entire QA lifecycle. Use these tools to ensure top-notch quality for your products.',
    placement: 'center',
  }
];

export const ticketsTourSteps: RouteStep[] = [
  {
    target: 'body',
    route: '/dashboard',
    title: 'Welcome to Tickets & Sprints',
    content: 'This tour will guide you step by step through ticket configurations, sprint planning, and the complete task lifecycle. Before moving forward, make sure you have created your Project first; otherwise, you can view the Project Tour.',
    placement: 'center',
    showProjectTourBtn: true,
  },
  {
    target: '[data-tour="tickets-setting-platform"]',
    route: '/tickets/settings',
    title: 'Platforms Configuration',
    content: 'Configure core team platforms and delivery departments for your organization.',
    placement: 'bottom',
    clickOnNext: true,
  },
  {
    target: '[data-tour="tickets-setting-create-platform-btn"]',
    route: '/tickets/settings',
    title: 'Add Platform',
    content: 'Use this button to add a new Platform option to your workspace.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-stack"]',
    route: '/tickets/settings',
    title: 'Technology Stacks',
    content: 'Manage available technology stacks used for project tagging and ticket filtering.',
    placement: 'bottom',
    clickOnNext: true,
  },
  {
    target: '[data-tour="tickets-setting-create-stack-btn"]',
    route: '/tickets/settings',
    title: 'Add Technology Stack',
    content: 'Use this button to add a new Tech Stack classification.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-priority"]',
    route: '/tickets/settings',
    title: 'Priorities & Urgency',
    content: 'Define priority levels and visual indicators for your tickets.',
    placement: 'bottom',
    clickOnNext: true,
  },
  {
    target: '[data-tour="tickets-setting-create-priority-btn"]',
    route: '/tickets/settings',
    title: 'Add Priority',
    content: 'Use this button to define a new Priority level for tickets.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-taskLevel"]',
    route: '/tickets/settings',
    title: 'Complexity & Story Points',
    content: 'Configure task difficulty levels and story point weighting for estimation.',
    placement: 'bottom',
    clickOnNext: true,
  },
  {
    target: '[data-tour="tickets-setting-create-taskLevel-btn"]',
    route: '/tickets/settings',
    title: 'Add Complexity Level',
    content: 'Use this button to define a new task complexity rating.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-taskType"]',
    route: '/tickets/settings',
    title: 'Work Types',
    content: 'Define classifications for your tasks (e.g. Feature, Bug, Maintenance, Refactor).',
    placement: 'bottom',
    clickOnNext: true,
  },
  {
    target: '[data-tour="tickets-setting-create-taskType-btn"]',
    route: '/tickets/settings',
    title: 'Add Work Type',
    content: 'Use this button to add a new Work Type categorization.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-setting-status"]',
    route: '/tickets/settings',
    title: 'Lifecycle Statuses',
    content: 'Set up your workflow lifecycle stages (To Do, In Progress, Code Review, Completed).',
    placement: 'bottom',
    clickOnNext: true,
  },
  {
    target: '[data-tour="tickets-setting-create-status-btn"]',
    route: '/tickets/settings',
    title: 'Add Lifecycle Status',
    content: 'Use this button to define a new lifecycle status for your workflow.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-create-sprint"]',
    route: '/tickets/plans',
    title: 'Plan New Sprint',
    content: 'Click "Plan New Sprint" to start a new sprint cycle for your project with defined timelines and objectives.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-activate-sprint"]',
    route: '/tickets/plans',
    title: 'Activate Sprint',
    content: 'Click "Start Sprint" to activate your planned sprint. Note: Only one sprint can be active per project at any time. Complete your active sprint before activating another.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-project-view"]',
    route: '/tickets/select',
    title: 'Select Project & Sprint Board',
    content: 'Switch projects and access your active sprint board or backlog view.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="tickets-create"]',
    route: '/tickets/select',
    title: 'Create Tickets',
    content: 'Create tickets using Instant Creation for fast typing, Manual Creation for full details, or AI generation with Zai. Note: New tickets start in the Backlog by default.',
    placement: 'bottom',
  },
  {
    target: '.ticket-creation-slider',
    route: '/tickets/select',
    title: 'Manual Ticket Creation',
    content: 'Create detailed tickets with precise specifications, assignments, and estimates.',
    placement: 'left',
  },
  {
    target: '[data-tour="ticket-manual-core"]',
    route: '/tickets/select',
    title: 'Core Context',
    content: 'Define the subject, target platform, and associate it with a specific project.',
    placement: 'left',
  },
  {
    target: '[data-tour="ticket-manual-desc"]',
    route: '/tickets/select',
    title: 'Rich Description',
    content: 'Provide full technical requirements. You can use formatting to structure your thoughts.',
    placement: 'left',
  },
  {
    target: '[data-tour="ticket-manual-specs"]',
    route: '/tickets/select',
    title: 'Execution Specs',
    content: 'Set priority level, technical category, story points, and estimated hours.',
    placement: 'left',
  },
  {
    target: '[data-tour="ticket-manual-ownership"]',
    route: '/tickets/select',
    title: 'Ownership & Timeline',
    content: 'Assign the ticket to a team member and define start and end dates.',
    placement: 'left',
  },
  {
    target: '[data-tour="ticket-manual-submit"]',
    route: '/tickets/select',
    title: 'Create Ticket',
    content: 'Click here to finalize and create your new ticket!',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-recent-created-btn"]',
    route: '/tickets/select',
    title: 'Created Ticket Overview',
    content: 'Click this created ticket button to immediately open its details drawer.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="tickets-drawer-add-sprint"]',
    route: '/tickets/select',
    title: 'Add to Sprint',
    content: 'Click "Add to Sprint" to immediately move this ticket from the backlog into your active sprint.',
    placement: 'bottom',
    spotlightClicks: true,
    clickOnNext: true,
  },
  {
    target: '[data-tour="tickets-drawer-add-sprint-confirm"]',
    route: '/tickets/select',
    title: 'Confirm Add to Sprint',
    content: 'Click "Add to Sprint" in the confirmation box to move the ticket.',
    placement: 'bottom',
    spotlightClicks: true,
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="tickets-drawer-create-doc"]',
    route: '/tickets/select',
    title: 'Create & Link Docs',
    content: 'Click "Create Doc" to link or generate a new Document Hub wiki, runbook, or technical spec for this ticket.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-drawer-share"]',
    route: '/tickets/select',
    title: 'Share Ticket',
    content: 'Copy and share the ticket link with teammates or external collaborators.',
    placement: 'bottom',
  },
  {
    target: '.full-tickets-drawer-tour-target .ant-drawer-content',
    route: '/tickets/select',
    title: 'Fill Ticket Details',
    content: 'Fill out your ticket specifications here — add detailed descriptions with Zai AI, set story points, assign developers, configure priorities, and create subtasks.',
    placement: 'center',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="tickets-drawer-close"]',
    route: '/tickets/select',
    title: 'Close Details Drawer',
    content: 'Click the close button or click Next to save changes and return to your tickets board.',
    placement: 'bottom',
    spotlightClicks: true,
    clickOnNext: true,
  },
  {
    target: '[data-tour="topnav-time-tracker"]',
    title: 'Time Tracking in Top Navigation',
    content: 'Track work duration in real-time right from the top navigation bar. Click the tracker to open the popover, select your project and ticket, and start the timer.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-burndown"]',
    route: '/tickets/select',
    title: 'Sprint Burndown',
    content: 'Click here to view full reports of the sprint, track progress, and analyze velocity.',
    placement: 'bottom',
    skipIfNotFound: true,
  },
  {
    target: '.ant-table-selection-column',
    route: '/tickets/select',
    title: 'Bulk Actions (Trash & Archive)',
    content: 'Select tickets using these checkboxes to reveal bulk actions. You can then move completed or unwanted tickets to the Archive or Trash to maintain a clean board.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="tickets-buckets-create"]',
    route: '/tickets/buckets',
    title: 'Buckets',
    content: 'Buckets allow you to organize tasks outside of sprints. You can create them from the Buckets page or during sprint completion.',
    placement: 'bottom',
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="tickets-complete-sprint"]',
    route: '/tickets/select',
    title: 'Complete Sprint',
    content: 'When your sprint finishes, click "Complete Sprint" directly from the active sprint header to resolve remaining tasks and complete the sprint.',
    placement: 'bottom',
    skipIfNotFound: true,
    spotlightClicks: true,
    clickOnNext: true,
  },
  {
    target: '.sprint-completion-modal .ant-modal-content',
    route: '/tickets/select',
    title: 'Sprint Completion Review',
    content: 'Review your sprint summary, handle any incomplete tickets, and finalize the sprint closure.',
    placement: 'center',
    skipIfNotFound: true,
  },
  {
    target: 'body',
    title: 'You are all set!',
    content: 'You are now ready to manage your entire Project & Ticket lifecycle. Plan sprints, track progress, and ship with confidence!',
    placement: 'center',
  }
];

export const documentHubTourSteps: RouteStep[] = [
  {
    target: 'body',
    route: '/documenthub',
    title: 'Document Hub',
    content: 'Your central knowledge base for specs, wikis, runbooks, and docs.',
    placement: 'center',
  },
  {
    target: '[data-tour="dochub-create-hub-btn"]',
    route: '/documenthub',
    title: 'Create Hub',
    content: 'Click to create a new Document Hub or generate one with AI.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="dochub-workspace-new-btn"]',
    title: 'Create Content',
    content: 'Use "+ New" to organize content into nested folders and rich documents.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-history-btn"]',
    title: 'Version History',
    content: 'Inspect previous versions, compare changes, and restore snapshots.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-link-project"]',
    route: '/documenthub',
    title: 'Link Project',
    content: 'Attach your hub to a project to group relevant documentation.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-link-ticket"]',
    route: '/documenthub',
    title: 'Link Ticket',
    content: 'Associate your hub with a ticket for immediate technical context.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-visibility-btn"]',
    route: '/documenthub',
    title: 'Visibility',
    content: 'Set visibility to Public or Private.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-share-btn"]',
    route: '/documenthub',
    title: 'Share',
    content: 'Share docs with teammates and manage permissions.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-star-btn"]',
    route: '/documenthub',
    title: 'Star Hubs',
    content: 'Star important hubs to pin them for 1-click access.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="dochub-upload-import"]',
    route: '/documenthub',
    title: 'Import & Upload',
    content: 'Upload files or import directly from Google Drive, Notion, and OneDrive.',
    placement: 'bottom',
  },
  {
    target: 'body',
    route: '/documenthub',
    title: 'All Set!',
    content: 'You are ready to create and collaborate on documentation!',
    placement: 'center',
  }
];

export const manualProjectTourSteps: RouteStep[] = [
  {
    target: 'body',
    route: '/projects/manage',
    title: 'Projects',
    content: 'Organize deliverables, define milestones, manage teams, and plan sprints.',
    placement: 'center',
  },
  {
    target: '[data-tour="project-create-btn"]',
    route: '/projects/manage',
    title: 'Create Project',
    content: 'Click "+ Add Project" to configure a new project workspace.',
    placement: 'bottom',
    spotlightClicks: true,
    clickOnNext: true,
  },
  {
    target: '[data-tour="project-form-details"]',
    title: 'Project Details',
    content: 'Define your Project Name, unique issue key, status, and description.',
    placement: 'left',
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="project-form-team"]',
    title: 'Team Access',
    content: 'Assign a Project Manager and select team members who can contribute.',
    placement: 'left',
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="project-form-timeline"]',
    title: 'Timeline & Repositories',
    content: 'Set timeline dates and attach repository URLs for code tracking.',
    placement: 'left',
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="project-filters-btn"]',
    route: '/projects/manage',
    title: 'Filter Projects',
    content: 'Filter your projects by status, manager, and date ranges.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="project-row-actions"]',
    route: '/projects/manage',
    title: 'Project Actions',
    content: 'View the project board, edit settings, or delete projects.',
    placement: 'left',
  },
  {
    target: 'body',
    route: '/projects/manage',
    title: 'All Set!',
    content: 'You are ready to manage projects and track deliverables with your team!',
    placement: 'center',
  }
];

export const importMigrationTourSteps: RouteStep[] = [
  {
    target: 'body',
    route: '/integrations',
    title: 'Integrations & Migration',
    content: 'Connect your favorite tools and easily migrate projects, issues, and calendars into your workspace.',
    placement: 'center',
  },
  {
    target: '[data-tour="integration-issue-trackers"]',
    route: '/integrations',
    title: 'Jira & Linear',
    content: 'Connect Jira or Linear to sync your tasks and issue trackers instantly.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="integration-migration-btn"], [data-tour="integration-issue-trackers"]',
    route: '/integrations',
    title: 'Migrate Data',
    content: 'Click "Start Migration" to import boards and sprints. This runs in the background.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="integration-mail-calendar"]',
    route: '/integrations',
    title: 'Mail & Calendar',
    content: 'Connect Google Workspace, Microsoft 365, or Zoho to sync team emails and events.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="calendar-sync-btn"]',
    route: '/calendar',
    title: 'Sync Events',
    content: 'Click here to fetch the latest calendar events from your connected provider.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="calendar-create-event-btn"]',
    route: '/calendar',
    title: 'Create Event',
    content: 'Click "New event" to schedule meetings, invite attendees, and add video links.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="mail-sync-btn"], [data-tour="mail-connect-empty-btn"]',
    route: '/mail',
    title: 'Sync Mail',
    content: 'Sync your inbox to read emails from your connected provider.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="mail-compose-btn"]',
    route: '/mail',
    title: 'Compose Mail',
    content: 'Click "Compose" to write and send messages with AI assistance.',
    placement: 'bottom',
  },
  {
    target: 'body',
    route: '/mail',
    title: 'All Set!',
    content: 'Your integrations are active and ready to use.',
    placement: 'center',
  }
];export const adminSettingsTourSteps: RouteStep[] = [
  {
    target: 'body',
    route: '/settings',
    title: 'System Settings',
    content: 'Set up your workspace identity, company details, mail, and AI configurations.',
    placement: 'center',
  },
  {
    target: '[data-tour="settings-tab-system"]',
    route: '/settings',
    title: 'System Info',
    content: 'Manage your primary workspace identity and branding.',
    placement: 'bottom',
    spotlightClicks: true,
    clickOnNext: true,
  },
  {
    target: '[data-tour="settings-company-name"]',
    route: '/settings',
    title: 'Company Name',
    content: 'Update your official workspace display name.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="settings-company-logo"]',
    route: '/settings',
    title: 'Company Logo',
    content: 'Upload your brand logo for navigation and exports.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="settings-logo-crop-btn"], [data-tour="settings-company-logo"]',
    route: '/settings',
    title: 'Crop Logo',
    content: 'Click the edit icon to crop or adjust your logo.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="settings-save-branding-btn"]',
    route: '/settings',
    title: 'Save Changes',
    content: 'Click "Save" to apply your branding settings.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="settings-tab-company"]',
    route: '/settings',
    title: 'Company Details',
    content: 'Manage legal entity records and office locations.',
    placement: 'bottom',
    spotlightClicks: true,
    clickOnNext: true,
  },
  {
    target: '[data-tour~="settings-company-registered"]',
    route: '/settings',
    title: 'Registered Company',
    content: 'Edit your legal company name and tax ID.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour~="settings-company-address"]',
    route: '/settings',
    title: 'Registered Address',
    content: 'Manage the official address for invoices.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="settings-add-branch-btn"]',
    route: '/settings',
    title: 'Add Branch',
    content: 'Click "+ Add Branch" for multiple regional offices.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="settings-tab-mail"]',
    route: '/settings',
    title: 'Mail Config',
    content: 'Manage dispatch channels and active senders.',
    placement: 'bottom',
    spotlightClicks: true,
    clickOnNext: true,
  },
  {
    target: '[data-tour="settings-mail-active-sender"], [data-tour="settings-mail-connect-empty"]',
    route: '/settings',
    title: 'Active Sender',
    content: 'Select the verified email account for dispatch.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="settings-tab-ai"]',
    route: '/settings',
    title: 'AI Provider',
    content: 'Manage your AI models and provider keys.',
    placement: 'bottom',
    spotlightClicks: true,
    clickOnNext: true,
  },
  {
    target: '[data-tour="ai-mode-platform"]',
    route: '/settings',
    title: 'Platform Mode',
    content: 'Use pre-configured bundled models. No API keys needed.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: '[data-tour="ai-settings-bundled-model"]',
    route: '/settings',
    title: 'Model',
    content: 'Select a bundled model for workspace AI features.',
    placement: 'bottom',
    spotlightClicks: true,
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="ai-settings-save-btn"]',
    route: '/settings',
    title: 'Save Config',
    content: 'Click "Save" to activate Platform Mode.',
    placement: 'bottom',
    spotlightClicks: true,
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="ai-mode-byo"]',
    route: '/settings',
    title: 'Bring your own key',
    content: 'Connect your own OpenAI, Anthropic, or Gemini keys.',
    placement: 'bottom',
    spotlightClicks: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="ai-settings-provider"]',
    route: '/settings',
    title: 'Provider',
    content: 'Choose your AI provider.',
    placement: 'bottom',
    spotlightClicks: true,
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="ai-settings-api-key"]',
    route: '/settings',
    title: 'API Key',
    content: 'Paste your private API key.',
    placement: 'bottom',
    spotlightClicks: true,
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="ai-settings-base-url"]',
    route: '/settings',
    title: 'Base URL',
    content: 'Enter custom API endpoint if required.',
    placement: 'bottom',
    spotlightClicks: true,
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="ai-settings-byo-model"]',
    route: '/settings',
    title: 'Model',
    content: 'Type the exact model identifier to use.',
    placement: 'bottom',
    spotlightClicks: true,
    skipIfNotFound: true,
  },
  {
    target: '[data-tour="ai-settings-save-btn"]',
    route: '/settings',
    title: 'Save AI Config',
    content: 'Click "Save" to activate your AI preferences.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  {
    target: 'body',
    route: '/settings',
    title: 'All Set!',
    content: 'Your system settings are fully configured.',
    placement: 'center',
  }
];

export const rolesTourSteps: RouteStep[] = [
  {
    target: 'body',
    route: '/roles',
    title: 'Roles & RBAC',
    content: 'Manage access by assigning custom roles and granular permissions across your workspace.',
    placement: 'center',
  },
  {
    target: '[data-tour="roles-create-btn"]',
    route: '/roles',
    title: 'Create Role',
    content: 'Click "Create Role" to define custom permissions for specific teams.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="roles-sidebar-views"]',
    route: '/roles',
    title: 'Roles Overview',
    content: 'Filter roles into built-in System roles and Custom organizational roles.',
    placement: 'right',
  },
  {
    target: '[data-tour="roles-table-perms"]',
    route: '/roles',
    title: 'Permissions Matrix',
    content: 'Click "Edit permissions" to configure granular module access.',
    placement: 'bottom',
  },
  {
    target: '[data-tour="roles-table-members"]',
    route: '/roles',
    title: 'Assign Members',
    content: 'Assign teammates or update their roles from the Manage Members drawer.',
    placement: 'bottom',
  },
  {
    target: 'body',
    route: '/roles',
    title: 'All Set!',
    content: 'Your custom roles and permissions are fully configured.',
    placement: 'center',
  }
];

export const orgStructureTourSteps: RouteStep[] = [
  // 1. Greeting
  {
    target: 'body',
    route: '/org-structure/overview',
    title: 'Organization Structure',
    content: 'Model your company hierarchy: employment types, grades, departments, and positions.',
    placement: 'center',
  },
  // 2. Employment Type in side nav
  {
    target: '[data-tour="org-nav-employment-types"]',
    route: '/org-structure/overview',
    title: 'Employment Types',
    content: 'Define contracts like Full-Time, Contractor, and Intern.',
    placement: 'right',
    spotlightClicks: true,
  },
  // 3. Open Employment Type & highlight create button
  {
    target: '[data-tour="org-employment-types-create-btn"]',
    route: '/org-structure/employment-types',
    title: 'Create Type',
    content: 'Click "+ New Type" to add employment categories.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  // 4. Grades in side nav
  {
    target: '[data-tour="org-nav-grades"]',
    route: '/org-structure/employment-types',
    title: 'Grades',
    content: 'Configure compensation bands and seniority tiers.',
    placement: 'right',
    spotlightClicks: true,
  },
  // 5. Open Grades & highlight create button
  {
    target: '[data-tour="org-grades-create-btn"]',
    route: '/org-structure/grades',
    title: 'Create Grade',
    content: 'Click "+ New Grade" to define compensation tiers.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  // 6. Departments in side nav
  {
    target: '[data-tour="org-nav-departments"]',
    route: '/org-structure/grades',
    title: 'Departments',
    content: 'Manage functional business units and divisions.',
    placement: 'right',
    spotlightClicks: true,
  },
  // 7. Open Departments & highlight create button
  {
    target: '[data-tour="org-departments-create-btn"]',
    route: '/org-structure/departments',
    title: 'Create Department',
    content: 'Click "+ New Department" to establish core units.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  // 8. Sub-Departments in side nav
  {
    target: '[data-tour="org-nav-sub-departments"]',
    route: '/org-structure/departments',
    title: 'Sub-Departments',
    content: 'Organize specialized teams under parent departments.',
    placement: 'right',
    spotlightClicks: true,
  },
  // 9. Open Sub-Departments & highlight create button
  {
    target: '[data-tour="org-sub-departments-create-btn"]',
    route: '/org-structure/sub-departments',
    title: 'Create Sub-Department',
    content: 'Click "+ New Sub-Department" to nest specialized teams.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  // 10. Positions in side nav
  {
    target: '[data-tour="org-nav-positions"]',
    route: '/org-structure/sub-departments',
    title: 'Positions',
    content: 'Configure exact job designations and roles.',
    placement: 'right',
    spotlightClicks: true,
  },
  // 11. Open Positions & highlight create button
  {
    target: '[data-tour="org-positions-create-btn"]',
    route: '/org-structure/positions',
    title: 'Create Position',
    content: 'Click "+ New Position" to create job designations.',
    placement: 'bottom',
    spotlightClicks: true,
  },
  // 12. Overview in side nav
  {
    target: '[data-tour="org-nav-overview"]',
    route: '/org-structure/positions',
    title: 'Overview',
    content: 'Return here to inspect your complete company hierarchy.',
    placement: 'right',
    spotlightClicks: true,
  },
  // 13. Grade Distribution
  {
    target: '[data-tour="org-overview-grades-list"]',
    route: '/org-structure/overview',
    title: 'Grade Distribution',
    content: 'Select a grade to inspect mapped positions and departments.',
    placement: 'right',
    spotlightClicks: true,
  },
  // 14. Hierarchy Visualization
  {
    target: '[data-tour="org-overview-tree"]',
    route: '/org-structure/overview',
    title: 'Hierarchy Tree',
    content: 'Expand the visual chart to trace reporting relationships.',
    placement: 'left',
  },
  // 15. Final Completion
  {
    target: 'body',
    route: '/org-structure/overview',
    title: 'All Set!',
    content: 'Your company hierarchy is ready for assignments.',
    placement: 'center',
  }
];

export const membersTourSteps: RouteStep[] = [
  // Step 1: Greeting
  {
    target: 'body',
    route: '/members',
    title: 'Members Directory',
    content: 'Manage your team directory, onboard members, configure access, and set working shifts.',
    placement: 'center',
  },
  // Step 2: Create Member button
  {
    target: '[data-tour="members-create-btn"]',
    route: '/members',
    title: 'Add Member',
    content: 'Click "+ Add Member" to invite a new teammate.',
    placement: 'right',
    spotlightClicks: true,
    clickOnNext: true,
  },
  // Step 3: Profile Details
  {
    target: '[data-tour="member-drawer-profile-details"]',
    route: '/members',
    title: 'Profile Details',
    content: 'Enter the teammate’s name, emails, and phone number.',
    placement: 'left',
    spotlightClicks: true,
  },
  // Step 4: Access (with role tour & org tour jump buttons)
  {
    target: '[data-tour="member-drawer-access"]',
    route: '/members',
    title: 'Access & Roles',
    content: 'Assign roles, positions, and reporting managers to define permissions and hierarchy.',
    placement: 'left',
    spotlightClicks: true,
    showRoleTourBtn: true,
    showOrgTourBtn: true,
  },
  // Step 5: Schedule
  {
    target: '[data-tour="member-drawer-schedule"]',
    route: '/members',
    title: 'Schedule',
    content: 'Set attendance shifts, active working days, and minimum daily hours.',
    placement: 'left',
    spotlightClicks: true,
  },
  // Step 6: Choose which mail to send Welcome Notification
  {
    target: '[data-tour="member-drawer-welcome-notification"]',
    route: '/members',
    title: 'Send Invitation',
    content: 'Choose an email to send the welcome link and temporary password.',
    placement: 'left',
    spotlightClicks: true,
  },
  // Step 9: Actions
  {
    target: '[data-tour="members-table-actions"]',
    route: '/members',
    title: 'Member Actions',
    content: 'Use the (•••) menu to edit details, view history, or delete a member.',
    placement: 'left',
  },
  // Step 10: Filters
  {
    target: '[data-tour="members-sidebar-filters"], [data-tour="members-search-bar"]',
    route: '/members',
    title: 'Filters & Search',
    content: 'Find members quickly using sidebar filters or the top search bar.',
    placement: 'right',
  },
  // Final Completion
  {
    target: 'body',
    route: '/members',
    title: 'All Set!',
    content: 'Your team directory is ready for collaboration.',
    placement: 'center',
  }
];



